### PR TITLE
[Nexus] API related update

### PR DESCRIPTION
**Pull request by AlwinEsch**
Related to xbmc/xbmc#20705 and xbmc/xbmc#20710

### CODE REVIEW

**Review by garbear — APPROVED** [review]

**Comment by garbear** [comment]
@AlwinEsch I have a report of a crash from @razzeee: https://paste.kodi.tv/gukewutuci . Any ideas from you?

**Comment by AlwinEsch** [comment]
> @AlwinEsch I have a report of a crash from @razzeee: https://paste.kodi.tv/gukewutuci . Any ideas from you?

Have added a fix about, the "addon.h" was not in cmake and not checked about kodi header usage."

**Comment by razzeee** [comment]
Can you maybe fix this before this api breakage lands? Would be curious to update the flatpak beta, without having to update everything again.

**Comment by AlwinEsch** [comment]
Have separated to another request and here now alone about API change.

**Pull request merged**
